// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Package pages holds top-level, full-page templ templates. Phase 0 has a

// single placeholder page proving the chi + templ + Tailwind + Basecoat

// pipeline works end to end (docs/IMPLEMENTATION_PLAN.md Phase 0).

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Sadqa Ledger</title><link rel=\"stylesheet\" href=\"/static/vendor/basecoat/basecoat.min.css\"><link rel=\"stylesheet\" href=\"/static/css/output.css\"><script src=\"/static/vendor/basecoat/basecoat.min.js\" defer></script></head><body class=\"bg-background text-foreground font-sans min-h-screen\"><main class=\"mx-auto max-w-xl px-6 py-16\"><div class=\"card\"><header><h2>Sadqa Ledger</h2><p>Phase 0 scaffolding — chi + templ + Tailwind v4 + Basecoat.</p></header><section><p class=\"text-muted-foreground\">If this card has a border, rounded corners, and a solid teal button below, Basecoat and the project's Tailwind theme are both wired up correctly.</p></section><footer><button class=\"btn\" data-variant=\"primary\">It works</button></footer></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
